# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 01:10
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('managr_entities', '0011_managruser_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(default=0)),
                ('task_type', models.CharField(blank=True, choices=[('task', 'task'), ('project', 'project'), ('milestone', 'milestone')], default=0, max_length=9)),
                ('parent_id', models.BigIntegerField(null=True)),
                ('level', models.PositiveIntegerField(null=True)),
                ('progress', models.FloatField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)])),
                ('task_open', models.BooleanField(default=True)),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.BigIntegerField()),
                ('target', models.BigIntegerField()),
                ('task_type', models.CharField(choices=[(0, 'finish to start'), (1, 'start to start'), (2, 'finish to finish'), (3, 'start to finish')], default='0', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='client_contact_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='project',
            name='company_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_owner', to='managr_entities.Company'),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor_contact_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='project',
            name='project_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='user_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestonelink',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.Project'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.Project'),
        ),
    ]
