# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
