# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 02:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=10)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('task_type', models.CharField(blank=True, choices=[('task', 'task'), ('project', 'project'), ('milestone', 'milestone')], default=0, max_length=9)),
                ('parent_id', models.IntegerField(null=True)),
                ('level', models.PositiveIntegerField(null=True)),
                ('progress', models.FloatField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)])),
                ('task_open', models.BooleanField(default=True)),
                ('end_date', models.CharField(blank=True, max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.Project')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField()),
                ('target', models.IntegerField()),
                ('task_type', models.CharField(choices=[(0, 'finish to start'), (1, 'start to start'), (2, 'finish to finish'), (3, 'start to finish')], default='0', max_length=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.Project')),
            ],
        ),
    ]
