# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_project_project_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.IntegerField(null=True),
        ),
    ]
