# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_milestone_milestonelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
