# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0005_auto_20170419_0422'),
        ('project_management', '0004_auto_20170422_0830'),
    ]

    operations = [
    ]
