# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20161201_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploaded_file',
            field=models.FileField(null=True, upload_to='documents/temp_uploaded_documents/'),
        ),
    ]
