# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20161201_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
