# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 20:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managr_entities', '0003_company'),
        ('project_proposal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('details', django.contrib.postgres.fields.hstore.HStoreField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managr_entities.Company')),
            ],
        ),
    ]
