# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 00:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_proposal', '0003_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='budget',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='contact_number',
            field=models.CharField(default='(123) 456-7890', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='end_date',
            field=models.DateField(default='2017-04-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='start_date',
            field=models.DateField(default='2017-04-19'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='address',
            field=models.CharField(default='Default Address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='budget',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='contact_number',
            field=models.CharField(default='(123) 456-7890', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='end_date',
            field=models.DateField(default='2017-04-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='start_date',
            field=models.DateField(default='2017-04-19'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
