# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_proposal', '0003_bid_bid_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bid',
            name='proposal_removed',
            field=models.BooleanField(default=False),
        ),
    ]
