# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project_proposal', '0004_auto_20170411_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposal_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
