# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 20:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_proposal', '0004_auto_20170409_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='details',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
