# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_proposal', '0005_proposal_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managr_entities.Company'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managr_entities.Company'),
        ),
    ]
