# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 21:39
from __future__ import unicode_literals

from django.db import models, migrations
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    	HStoreExtension(),
    ]
