# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managr_entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managruser',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Construction Management'), (1, 'Client'), (2, 'Construction Worker')], default=0),
        ),
    ]
