# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 23:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managr_entities', '0002_managruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_type', models.IntegerField(choices=[(0, 'Construction'), (1, 'Client')], default=0)),
                ('attributes', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
    ]
