# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managr_entities', '0004_company_company_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.IntegerField(choices=[(0, 'construction'), (1, 'client')], default=0),
        ),
    ]
