# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 22:16
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managr_entities', '0005_auto_20170124_0143'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='managruser',
            managers=[
            ],
        ),
    ]
