# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 14:21
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models
import managr_entities.app_managers.managr_user


class Migration(migrations.Migration):

    dependencies = [
        ('managr_entities', '0006_auto_20170222_2216'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='managruser',
            managers=[
                ('objects', managr_entities.app_managers.managr_user.ManagrUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='managruser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
