# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managr_entities', '0007_auto_20170223_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='managruser',
            name='session_token',
            field=models.UUIDField(null=True),
        ),
    ]
