# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managr_entities', '0009_auto_20170412_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_key',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
