# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_project'),
        ('managr_entities', '0010_company_company_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='managruser',
            name='projects',
            field=models.ManyToManyField(to='project_management.Project'),
        ),
    ]
