# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 04:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managr_entities', '0011_managruser_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='managruser',
            name='shifts',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
            preserve_default=False,
        ),
    ]
