# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managr_entities', '0012_managruser_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='managruser',
            name='is_clocked_in',
            field=models.BooleanField(default=False),
        ),
    ]
